project_id = "oticlgskebuoswlbpucb"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[functions.get-org-dockets]
verify_jwt = false

[edge_runtime]
enabled = true
ip_version = "dual"
port = 54321
inspector_port = 8083